import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { PrimeReactProvider } from "primereact/api";
import Head from "next/head";
import "primereact/resources/themes/lara-dark-cyan/theme.css";

const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${montserrat.className} antialiased`}
      >
        <PrimeReactProvider>{children}</PrimeReactProvider>
      </body>
    </html>
  );
}
